cs130-w21/12

frontend/nginx.conf

Minor Change to nginx.conf to fix routing issue on Heroku

---

frontend/src/data/preferences.js
frontend/src/pages/Main.js

add a new option "No preference" and will set val of preference to null
resolves #52

fixed issue #52

---

frontend/src/App.js

Functionality that requires login before accessing /profile and /my_recipes. If the user is not logged in, they will be redirected to the login/sign-up page.

Added protection for /profile and /my_recipes

---

backend/Dockerfile.prod
backend/config-prod.json
backend/config.js
backend/model/database.js
backend/route/search.js
heroku.yml

Response to issue #60.
Added configuration files and Dockerfile for production. Heroku is now able to deploy our branch.
Found an issue with the /recipes/random endpoint because it conflicted with /recipes/{id} endpoint. Fixed this by changing GET /recipes/random to GET /recipes. Apologies for the back and forth. It should actually work flawlessly now.

Added deployment fix, endpoint fix, minor clean up

---

frontend/src/components/RecipeCard.js

Rolled back for recipe card

---

backend/gateway/query-gateway.js
backend/index.js
backend/model/Bookmark.js
backend/model/Recipe.js
backend/model/User.js
backend/model/sync.js
backend/postgres/bookmark-query.js
backend/postgres/recipe-query.js
backend/postgres/user-query.js
backend/route/bookmark.js
backend/route/profile.js
backend/service/bookmark-service.js
backend/service/profile-service.js
backend/service/recipe-service.js

Restructured backend packages. Added /backend/postgres/ package to reduce clutter in /backend/gateway/query-gateway.js.
Completed flow for bookmarking, including adding, deleting, getting all, and getting one bookmark(s). Issue #64 complete.
Completed flow for saving recipes to database upon receiving response from Spoonacular API request. Addition to previously completed issue.
Added flow for creating new user. Issue #67 partially complete.
Merging back into branch 10 for convenience, since this branch was branched out from branch 10.

Completed Flow for Bookmarking, Creating New User, Saving Recipes

---

frontend/src/pages/Main.js
frontend/src/styles/Main.css

Fix Main Page Styling Bug

---

frontend/src/App.js
frontend/src/pages/RecipeDetails.js

Integrated the back-end with the recipe details page.

65  integration

---

backend/gateway/recipe-gateway.js

Response to issue #78.
Error was in bad query parameter in gateway.

Fixed bad Spoonacular results

---

frontend/src/pages/Main.js
frontend/src/styles/Main.css
frontend/src/styles/styles.js

Implemented lucky button so it worked.
Added spinner for UI

16  implement lucky function

---

frontend/src/pages/Main.js

Fix Recipe Details route

---

.eslintignore
backend/config-prod.json
backend/config.json
backend/gateway/recipe-gateway.js
backend/route/search.js
backend/service/recipe-service.js

Fixed Backend Random Recipe Endpoint

---

frontend/src/__test__/RecipeCollection.test.js
frontend/src/pages/Main.js

Fix Recipe Details for the updated random recipe route.
Fix Frontend Testing.

16 implement lucky button

---

app.json

Just added one file to the main project directory what will cause all API review apps to build/run in our docker environment.

Created the app.json file

---

.github/workflows/backendCI.yml

Changed the CI to run for only pushes to master.

updated backendCI.yml

---

frontend/src/components/UserInput.js
frontend/src/contexts/contexts.js
frontend/src/pages/Main.js
frontend/src/pages/RecipeCollection.js

Fix Frontend Searching Problem

---

frontend/src/components/RecipeCard.js
frontend/src/pages/Main.js
frontend/src/pages/RecipeCollection.js
frontend/src/styles/Main.css

Added spinners to frontend when fetching data, for user experience.
#128

19  spinner enhancement

---

frontend/src/components/AppHeader.js
frontend/src/pages/RecipeCollection.js
frontend/src/pages/RecipeDetails.js

made bookmarking functional, but my bookmarked recipes still show incorrect status
need to work on it more, but since it fixes some of the bugs, merge to master

Preliminary bugfix... 

---

frontend/src/__test__/RecipeCollection.test.js
frontend/src/__test__/RecipeDetails.test.js
frontend/src/pages/RecipeCollection.js

Bug Fix for testing

---

frontend/src/pages/RecipeCollection.js
frontend/src/pages/RecipeDetails.js

Remove redundant console.log statements
